// <auto-generated />
using Investments.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Investments.Migrations
{
    [DbContext(typeof(InvestmentsContext))]
    partial class InvestmentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Investments.Models.Optimazation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<int>("dividentsA");

                    b.Property<int>("dividentsB");

                    b.Property<int>("investmentA");

                    b.Property<int>("investmentB");

                    b.Property<int>("limitA");

                    b.Property<int>("limitB");

                    b.Property<int>("result");

                    b.Property<int>("sum");

                    b.HasKey("ID");

                    b.ToTable("Optimazation");
                });
#pragma warning restore 612, 618
        }
    }
}
